import os
import hashlib
import json

# ── Config ───────────────────────────────────────────────────────
BASE_URL = "https://raw.githubusercontent.com/lloganisawsome/TAC/refs/heads/main/"
ENTRY    = "home.html"
OUTPUT_MANIFEST = "manifest.json"
OUTPUT_LOADER   = "loader.js"

# File extensions to include
INCLUDE_EXT = {
    ".html", ".htm", ".css", ".js", ".json",
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico",
    ".mp3", ".wav", ".ogg", ".mp4", ".webm",
    ".ttf", ".woff", ".woff2", ".eot",
    ".txt", ".md", ".xml"
}

# Files/folders to always skip
SKIP_NAMES = {
    "generate_manifest.py", "manifest.json", "loader.js",
    ".git", ".github", "node_modules", "__pycache__"
}

# ── Scan directory ───────────────────────────────────────────────
def scan_files(root_dir):
    files = {}
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Skip hidden/ignored folders in-place
        dirnames[:] = [d for d in dirnames if d not in SKIP_NAMES and not d.startswith(".")]

        for filename in filenames:
            if filename in SKIP_NAMES or filename.startswith("."):
                continue
            ext = os.path.splitext(filename)[1].lower()
            if ext not in INCLUDE_EXT:
                continue

            abs_path = os.path.join(dirpath, filename)
            # Relative path from root, forward slashes
            rel_path = os.path.relpath(abs_path, root_dir).replace("\\", "/")

            # Hash the file for cache busting
            with open(abs_path, "rb") as f:
                file_hash = hashlib.md5(f.read()).hexdigest()[:8]

            full_url = BASE_URL + rel_path
            files[rel_path] = {
                "url":  full_url,
                "hash": file_hash
            }

    return files

# ── Write manifest.json ──────────────────────────────────────────
def write_manifest(files, root_dir):
    # Version = hash of all file hashes combined
    combined = "".join(v["hash"] for v in sorted(files.values(), key=lambda x: x["url"]))
    version  = hashlib.md5(combined.encode()).hexdigest()[:10]

    manifest = {
        "version": version,
        "files":   {path: data["hash"] for path, data in files.items()}
    }

    out = os.path.join(root_dir, OUTPUT_MANIFEST)
    with open(out, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"[+] manifest.json written ({len(files)} files, version {version})")
    return version

# ── Write loader.js ──────────────────────────────────────────────
def write_loader(files, version, root_dir):
    # Build the file list as a JS object { "path": "fullURL", ... }
    file_entries = "\n".join(
        f'  "{path}": "{data["url"]}",'
        for path, data in sorted(files.items())
    )

    # Obfuscate the base URL by splitting it into parts and joining at runtime
    url_parts = [BASE_URL[:20], BASE_URL[20:40], BASE_URL[40:]]
    url_parts_js = json.dumps(url_parts)

    loader = f"""// loader.js — auto-generated by generate_manifest.py
// DO NOT EDIT MANUALLY — re-run the script to regenerate

(function() {{

// ── Obfuscated base URL ──────────────────────────────────────────
const __p = {url_parts_js};
const BASE = __p.join("");
const ENTRY = "{ENTRY}";

// ── File list (path → full raw URL) ─────────────────────────────
const FILES = {{
{file_entries}
}};

// ── Build page shell ─────────────────────────────────────────────
document.title  = "Loading...";
document.body.style.cssText = "margin:0;background:#111;overflow:hidden";
document.body.innerHTML = `
  <div id="ui" style="position:fixed;inset:0;display:flex;flex-direction:column;
    align-items:center;justify-content:center;gap:12px;color:#fff;
    font-family:sans-serif;background:#111">
    <div id="status" style="font-size:14px;opacity:.8">Starting...</div>
    <div style="width:260px;height:4px;background:#2a2a2a;border-radius:2px">
      <div id="bar" style="height:100%;width:0;background:#4af;
        border-radius:2px;transition:width .3s"></div>
    </div>
  </div>
  <iframe id="frame" style="width:100%;height:100vh;border:none;display:none"
    allow="autoplay;fullscreen"></iframe>
`;

const ui     = document.getElementById("ui");
const bar    = document.getElementById("bar");
const status = document.getElementById("status");
const frame  = document.getElementById("frame");

const setStatus = (msg, pct) => {{
  status.textContent = msg;
  if (pct != null) bar.style.width = pct + "%";
}};

// ── IndexedDB ────────────────────────────────────────────────────
const IDB = {{
  db: null,
  open: () => new Promise((res, rej) => {{
    const r = indexedDB.open("__sitecache", 1);
    r.onupgradeneeded = e => e.target.result.createObjectStore("f");
    r.onsuccess = e => {{ IDB.db = e.target.result; res(); }};
    r.onerror = rej;
  }}),
  get: k => new Promise((res, rej) => {{
    const r = IDB.db.transaction("f","readonly").objectStore("f").get(k);
    r.onsuccess = () => res(r.result ?? null);
    r.onerror = rej;
  }}),
  set: (k, v) => new Promise((res, rej) => {{
    const r = IDB.db.transaction("f","readwrite").objectStore("f").put(v, k);
    r.onsuccess = res; r.onerror = rej;
  }}),
  del: k => new Promise((res, rej) => {{
    const r = IDB.db.transaction("f","readwrite").objectStore("f").delete(k);
    r.onsuccess = res; r.onerror = rej;
  }})
}};

// ── URL helpers ──────────────────────────────────────────────────
const isAbs = u => /^(https?:|data:|blob:|#|javascript:|mailto:)/.test(u);

function resolveURL(dir, rel) {{
  if (!rel || isAbs(rel)) return rel;
  if (rel.startsWith("//")) return "https:" + rel;
  if (rel.startsWith("/")) return BASE + rel.slice(1);
  // Collapse ../ segments
  const stack = (dir + rel).split("/");
  const out = [];
  for (const s of stack) {{
    if (s === "..") out.pop();
    else if (s !== ".") out.push(s);
  }}
  return out.join("/");
}}

// ── HTML rewriter ────────────────────────────────────────────────
function rewriteHTML(html, filePath) {{
  const dir = BASE + filePath.replace(/[^\\/]*$/, "");
  const res = u => resolveURL(dir, u);

  const injected = `<script>
(function(){{
  const __d="${{dir}}";
  const __r=u=>/^(https?:|data:|blob:|#|javascript:)/.test(u)?u:__d+u;
  const _f=window.fetch;
  window.fetch=(u,o)=>_f(__r(String(u)),o);
  const _x=XMLHttpRequest.prototype.open;
  XMLHttpRequest.prototype.open=function(m,u,...a){{return _x.call(this,m,__r(String(u)),...a);}};
  document.addEventListener('click',e=>{{
    const a=e.target.closest('a[href]');
    if(!a)return;
    const h=a.getAttribute('href');
    if(!h||h.startsWith('#')||/^(https?:|mailto:|javascript:)/.test(h))return;
    e.preventDefault();
    window.parent.postMessage({{type:'nav',href:h}},'*');
  }});
}})();
<\\/script>`;

  return html
    .replace(/(src|href|action)="(?!https?:|data:|blob:|#|javascript:|mailto:)([^"]*?)"/g,
      (_,a,u) => `${{a}}="${{res(u)}}"`)
    .replace(/(src|href|action)='(?!https?:|data:|blob:|#|javascript:|mailto:)([^']*?)'/g,
      (_,a,u) => `${{a}}='${{res(u)}}'`)
    .replace(/url\\(\\s*["']?(?!https?:|data:|blob:)([^"'\\)]+?)["']?\\s*\\)/g,
      (_,u) => `url("${{res(u)}}")`)
    .replace(/<\\/head>/i, injected + "\\n</head>");
}}

// ── Fetch a file (cache-first) ───────────────────────────────────
async function getFile(path) {{
  const hit = await IDB.get("f:" + path);
  if (hit) return hit;
  const url = FILES[path] || (BASE + path);
  const r = await fetch(url);
  if (!r.ok) throw new Error("Fetch failed: " + path);
  const text = await r.text();
  await IDB.set("f:" + path, text);
  return text;
}}

// ── Load a page ──────────────────────────────────────────────────
let currentPath = ENTRY;
let blobURL = null;

async function loadPage(path) {{
  setStatus("Loading " + path, 80);
  currentPath = path;
  const raw  = await getFile(path);
  const html = rewriteHTML(raw, path);
  if (blobURL) URL.revokeObjectURL(blobURL);
  blobURL = URL.createObjectURL(new Blob([html], {{type:"text/html"}}));
  frame.src   = blobURL;
  ui.style.display    = "none";
  frame.style.display = "block";
}}

// ── Manifest update check ────────────────────────────────────────
async function checkUpdates() {{
  setStatus("Checking for updates...", 20);
  try {{
    const manifest = await fetch(BASE + "manifest.json?t=" + Date.now()).then(r => r.json());
    if (manifest.version !== localStorage.getItem("__ver")) {{
      setStatus("Updating changed files...", 50);
      for (const [file, hash] of Object.entries(manifest.files)) {{
        if (localStorage.getItem("__h:" + file) !== hash) {{
          await IDB.del("f:" + file);
          localStorage.setItem("__h:" + file, hash);
        }}
      }}
      localStorage.setItem("__ver", manifest.version);
    }}
  }} catch(e) {{ console.warn("Manifest check skipped:", e); }}
}}

// ── Navigation from iframe ───────────────────────────────────────
window.addEventListener('message', e => {{
  if (e.data?.type !== 'nav') return;
  const dir = BASE + currentPath.replace(/[^\\/]*$/, "");
  const abs  = resolveURL(dir, e.data.href);
  const path = abs.startsWith(BASE) ? abs.slice(BASE.length) : e.data.href;
  loadPage(path);
}});

// ── Boot ─────────────────────────────────────────────────────────
(async () => {{
  await IDB.open();
  await checkUpdates();
  await loadPage(ENTRY);
}})();

}})(); // end IIFE
"""

    out = os.path.join(root_dir, OUTPUT_LOADER)
    with open(out, "w") as f:
        f.write(loader)
    print(f"[+] loader.js written")

# ── Main ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    root = os.path.dirname(os.path.abspath(__file__))
    print(f"[*] Scanning: {root}")
    files = scan_files(root)
    print(f"[*] Found {len(files)} files")
    version = write_manifest(files, root)
    write_loader(files, version, root)
    print("[✓] Done — commit manifest.json and loader.js to GitHub")
